export const FAV_MOVIE_IMDB_IDS = [
    "tt4154756",
    "tt0418279",
    "tt0892769",
    "tt0086817",
    "tt0372784",
    "tt0103359",
    "tt0068646",
    "tt0071562",
    "tt0075314",
    "tt0110912",
    "tt3460252",
    "tt0266697",
    "tt0378194",
    "tt0468569",
    "tt1345836",
    "tt0120737",
    "tt0167260",
    "tt0167261",
    "tt7167658",
    "tt0448115",
    "tt0137523"
];

export const MenuItemProps = {
    menuItems: [
        {
            name: "Popular",
            path: "/"
        },
        {
            name: "Favorites",
            path: "/favorite"
        }
    ]
};

export const ModalProps = {
    cardItems: [
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/matthew.png",
            Title: "Matthew",
            date: "2018",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/matthew",
            imdbRating: "4.3"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/elliot.jpg",
            Title: "Elliot",
            date: "2005",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/elliot",
            imdbRating: "4.1"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/daniel.jpg",
            Title: "Daniel",
            date: "1996",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/daniel",
            imdbRating: "3.8"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/matthew.png",
            Title: "Matthew",
            date: "2018",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/matthew",
            imdbRating: "4.3"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/elliot.jpg",
            Title: "Elliot",
            date: "2005",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/elliot",
            imdbRating: "4.1"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/daniel.jpg",
            Title: "Daniel",
            date: "1996",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/daniel",
            imdbRating: "3.8"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/matthew.png",
            Title: "Matthew",
            date: "2018",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/matthew",
            imdbRating: "4.3"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/elliot.jpg",
            Title: "Elliot",
            date: "2005",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/elliot",
            imdbRating: "4.1"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/daniel.jpg",
            Title: "Daniel",
            date: "1996",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/daniel",
            imdbRating: "3.8"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/matthew.png",
            Title: "Matthew",
            date: "2018",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/matthew",
            imdbRating: "4.3"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/elliot.jpg",
            Title: "Elliot",
            date: "2005",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/elliot",
            imdbRating: "4.1"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/daniel.jpg",
            Title: "Daniel",
            date: "1996",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/daniel",
            imdbRating: "3.8"
        },
        {
            Poster: "https://react.semantic-ui.com/images/avatar/large/elliot.jpg",
            Title: "Elliot",
            date: "2005",
            Plot: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad architecto deserunt dolore doloremque eius error expedita, facilis fugiat id illum labore libero maiores nisi nobis optio perspiciatis sit veniam!",
            href: "/elliot",
            imdbRating: "4.1"
        }
    ]
};

// export const ModalProps = {
//     cardItems: [{
//         'Actors': 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans',
//         'Awards': 'N/A',
//         'BoxOffice': '$664,987,816',
//         'Country': 'USA',
//         'DVD': '14 Aug 2018',
//         'Director': 'Anthony Russo, Joe Russo',
//         'Genre': 'Action, Adventure, Sci-Fi',
//         'Language': 'English',
//         'Metascore': '68',
//         'Plot': 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg',
//         'Production': 'Walt Disney Pictures',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.5/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '85%'
//         }, {'Source': 'Metacritic', 'Value': '68/100'}],
//         'Released': '27 Apr 2018',
//         'Response': 'true',
//         'Runtime': '149 min',
//         'Title': 'Avengers: Infinity War',
//         'Type': 'movie',
//         'Website': 'http://marvel.com/movies/movie/223/avengers_infinity_war',
//         'Writer': 'Christopher Markus (screenplay by), Stephen McFeely (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by), Joe Simon (Captain America created by), Jack Kirby (Captain America created by), Steve Englehart (Star-Lord created by), Steve Gan (Star-Lord created by), Bill Mantlo (Rocket Raccoon created by), Keith Giffen (Rocket Raccoon created by), Jim Starlin (Thanos,  Gamora and Drax created by), Stan Lee (Groot created by), Larry Lieber (Groot created by), Jack Kirby (Groot created by), Steve Englehart (Mantis created by), Don Heck (Mantis created by)',
//         'Year': '2018',
//         'favorite': true,
//         'imdbID': 'tt4154756',
//         'imdbRating': '8.5',
//         'imdbVotes': '669,532'
//     }, {
//         'Actors': 'Shia LaBeouf, Megan Fox, Josh Duhamel, Tyrese Gibson',
//         'Awards': 'Nominated for 3 Oscars. Another 20 wins & 41 nominations.',
//         'BoxOffice': '$319,014,499',
//         'Country': 'USA',
//         'DVD': '16 Oct 2007',
//         'Director': 'Michael Bay',
//         'Genre': 'Action, Adventure, Sci-Fi',
//         'Language': 'English, Spanish',
//         'Metascore': '61',
//         'Plot': 'A long time ago, far away on the planet of Cybertron, a war is being waged between the noble Autobots (led by the wise Optimus Prime) and the devious Decepticons (commanded by the dreaded Megatron) for control over the Allspark, a mystical talisman that would grant unlimited power to whoever possesses it. The Autobots managed to smuggle the Allspark off the planet, but Megatron blasts off in search of it. He eventually tracks it to the planet of Earth (circa 1850), but his reckless desire for power sends him right into the Arctic Ocean, and the sheer cold forces him into a paralyzed state. His body is later found by Captain Archibald Witwicky, but before going into a comatose state Megatron uses the last of his energy to engrave into the Captain\'s glasses a map showing the location of the Allspark, and to send a transmission to Cybertron. Megatron is then carried away aboard the Captain\'s ship. A century later, Captain Witwicky\'s grandson Sam Witwicky (nicknamed Spike by his friends) buys his first car. To his shock, he discovers it to be Bumblebee, an Autobot in disguise who is to protect Spike, who possesses the Captain\'s glasses and the map engraved on them. But Bumblebee is not the only Transformer to have arrived on Earth - in the desert of Qatar, the Decepticons Blackout and Scorponok attack a U.S. military base, causing the Pentagon to send their special Sector Seven agents to capture all "specimens of this alien race." Spike and his girlfriend Mikaela find themselves in the midst of a grand battle between the Autobots and the Decepticons, stretching from Hoover Dam all the way to Los Angeles. Meanwhile, deep inside Hoover Dam, the cryogenically stored body of Megatron awakens.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNDg1NTU2OWEtM2UzYi00ZWRmLWEwMTktZWNjYWQ1NWM1OThjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
//         'Production': 'Dreamworks',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.1/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '58%'
//         }, {'Source': 'Metacritic', 'Value': '61/100'}],
//         'Released': '03 Jul 2007',
//         'Response': 'true',
//         'Runtime': '144 min',
//         'Title': 'Transformers',
//         'Type': 'movie',
//         'Website': 'http://www.transformersmovie.com/',
//         'Writer': 'Roberto Orci (screenplay), Alex Kurtzman (screenplay), John Rogers (story), Roberto Orci (story), Alex Kurtzman (story)',
//         'Year': '2007',
//         'favorite': true,
//         'imdbID': 'tt0418279',
//         'imdbRating': '7.1',
//         'imdbVotes': '570,463'
//     }, {
//         'Actors': 'Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera',
//         'Awards': 'Nominated for 2 Oscars. Another 25 wins & 60 nominations.',
//         'BoxOffice': '$216,900,000',
//         'Country': 'USA',
//         'DVD': '15 Oct 2010',
//         'Director': 'Dean DeBlois, Chris Sanders',
//         'Genre': 'Animation, Action, Adventure, Family, Fantasy',
//         'Language': 'English',
//         'Metascore': '74',
//         'Plot': "Long ago up North on the Island of Berk, the young Viking, Hiccup, wants to join his town's fight against the dragons that continually raid their town. However, his macho father and village leader, Stoik the Vast, will not allow his small, clumsy, but inventive son to do so. Regardless, Hiccup ventures out into battle and downs a mysterious Night Fury dragon with his invention, but can't bring himself to kill it. Instead, Hiccup and the dragon, whom he dubs Toothless, begin a friendship that would open up both their worlds as the observant boy learns that his people have misjudged the species. But even as the two each take flight in their own way, they find that they must fight the destructive ignorance plaguing their world.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg',
//         'Production': 'Paramount/DWA',
//         'Rated': 'PG',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.1/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '99%'
//         }, {'Source': 'Metacritic', 'Value': '74/100'}],
//         'Released': '26 Mar 2010',
//         'Response': 'true',
//         'Runtime': '98 min',
//         'Title': 'How to Train Your Dragon',
//         'Type': 'movie',
//         'Website': 'http://www.HowToTrainYourDragon.com/',
//         'Writer': 'William Davies (screenplay by), Dean DeBlois (screenplay by), Chris Sanders (screenplay by), Cressida Cowell (based on the book by), Marc Hyman (collaborating writer)',
//         'Year': '2010',
//         'favorite': true,
//         'imdbID': 'tt0892769',
//         'imdbRating': '8.1',
//         'imdbVotes': '612,050'
//     }, {
//         'Actors': 'Frank Welker, Peter Cullen, Corey Burton, Christopher Collins',
//         'Awards': 'N/A',
//         'Country': 'USA, Japan, South Korea',
//         'Director': 'N/A',
//         'Genre': 'Animation, Action, Adventure, Family, Sci-Fi',
//         'Language': 'English',
//         'Metascore': 'N/A',
//         'Plot': 'During the great Cybertronian War, the Autobots and the Decepticons crash landed on Earth. Millions of years later, geological activity revives the warring factions - the Decepticons want to strip Earth of its vast energy resources, and the Autobots seek to protect the inhabitants of Earth from that fate. And so an endless battle begins in a crucial race to find an energy source for their homeworld Cybertron.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BYjZkN2E5MDMtM2U1ZS00MGE2LTg1NzktYzZhYmVkNmJkYTk2XkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg',
//         'Rated': 'TV-Y7',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'}],
//         'Released': '17 Sep 1984',
//         'Response': 'true',
//         'Runtime': '30 min',
//         'Title': 'The Transformers',
//         'Type': 'series',
//         'Writer': 'N/A',
//         'Year': '1984–1987',
//         'favorite': true,
//         'imdbID': 'tt0086817',
//         'imdbRating': '8.0',
//         'imdbVotes': '18,737',
//         'totalSeasons': '4'
//     }, {
//         'Actors': 'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes',
//         'Awards': 'Nominated for 1 Oscar. Another 14 wins & 72 nominations.',
//         'BoxOffice': '$204,100,000',
//         'Country': 'USA, UK',
//         'DVD': '18 Oct 2005',
//         'Director': 'Christopher Nolan',
//         'Genre': 'Action, Adventure',
//         'Language': 'English, Urdu, Mandarin',
//         'Metascore': '70',
//         'Plot': "When his parents are killed, billionaire playboy Bruce Wayne relocates to Asia where he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as 'Batman'. But it doesn't stay quiet for long.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg',
//         'Production': 'Warner Bros. Pictures',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.2/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '84%'
//         }, {'Source': 'Metacritic', 'Value': '70/100'}],
//         'Released': '15 Jun 2005',
//         'Response': 'true',
//         'Runtime': '140 min',
//         'Title': 'Batman Begins',
//         'Type': 'movie',
//         'Website': 'https://www.warnerbros.com/batman-begins',
//         'Writer': 'Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)',
//         'Year': '2005',
//         'favorite': true,
//         'imdbID': 'tt0372784',
//         'imdbRating': '8.2',
//         'imdbVotes': '1,194,010'
//     }, {
//         'Actors': 'Kevin Conroy, Efrem Zimbalist Jr., Bob Hastings',
//         'Awards': 'Won 1 Primetime Emmy. Another 3 wins & 19 nominations.',
//         'Country': 'USA',
//         'Director': 'N/A',
//         'Genre': 'Animation, Action, Adventure, Family, Sci-Fi',
//         'Language': 'English',
//         'Metascore': 'N/A',
//         'Plot': "Heir to the Wayne family fortune, Bruce Wayne lives by day as a seemingly lavish playboy millionaire socialite, but by night assumes the role of his crime-fighting alter-ego: the caped crusader known as Batman. Throughout the Animated Series, Batman receives help from sidekicks Robin and Batgirl, as well as Police Commissioner Gordon, in protecting the streets of Gotham City from a large rogue's gallery of criminals, lunatics and nemeses.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg',
//         'Rated': 'TV-PG',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.9/10'}],
//         'Released': '05 Sep 1992',
//         'Response': 'true',
//         'Runtime': '23 min',
//         'Title': 'Batman: The Animated Series',
//         'Type': 'series',
//         'Writer': 'Bob Kane, Eric Radomski, Bruce Timm, Paul Dini, Bill Finger',
//         'Year': '1992–1995',
//         'favorite': true,
//         'imdbID': 'tt0103359',
//         'imdbRating': '8.9',
//         'imdbVotes': '75,615',
//         'totalSeasons': '4'
//     }, {
//         'Actors': 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano',
//         'Awards': 'Won 3 Oscars. Another 24 wins & 28 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '09 Oct 2001',
//         'Director': 'Francis Ford Coppola',
//         'Genre': 'Crime, Drama',
//         'Language': 'English, Italian, Latin',
//         'Metascore': '100',
//         'Plot': 'When the aging head of a famous crime family decides to transfer his position to one of his subalterns, a series of unfortunate events start happening to the family, and a war begins between all the well-known families leading to insolence, deportation, murder and revenge, and ends with the favorable successor being finally chosen.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'Paramount Pictures',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '9.2/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '98%'
//         }, {'Source': 'Metacritic', 'Value': '100/100'}],
//         'Released': '24 Mar 1972',
//         'Response': 'true',
//         'Runtime': '175 min',
//         'Title': 'The Godfather',
//         'Type': 'movie',
//         'Website': 'http://www.thegodfather.com',
//         'Writer': 'Mario Puzo (screenplay by), Francis Ford Coppola (screenplay by), Mario Puzo (based on the novel by)',
//         'Year': '1972',
//         'favorite': true,
//         'imdbID': 'tt0068646',
//         'imdbRating': '9.2',
//         'imdbVotes': '1,447,333'
//     }, {
//         'Actors': 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro',
//         'Awards': 'Won 6 Oscars. Another 11 wins & 20 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '24 May 2005',
//         'Director': 'Francis Ford Coppola',
//         'Genre': 'Crime, Drama',
//         'Language': 'English, Italian, Spanish, Latin, Sicilian',
//         'Metascore': '90',
//         'Plot': 'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'Paramount Pictures',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '9.0/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '97%'
//         }, {'Source': 'Metacritic', 'Value': '90/100'}],
//         'Released': '20 Dec 1974',
//         'Response': 'true',
//         'Runtime': '202 min',
//         'Title': 'The Godfather: Part II',
//         'Type': 'movie',
//         'Website': 'http://www.thegodfather.com/',
//         'Writer': 'Francis Ford Coppola (screenplay by), Mario Puzo (screenplay by), Mario Puzo (based on the novel by)',
//         'Year': '1974',
//         'favorite': true,
//         'imdbID': 'tt0071562',
//         'imdbRating': '9.0',
//         'imdbVotes': '1,005,269'
//     }, {
//         'Actors': 'Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito',
//         'Awards': 'Nominated for 4 Oscars. Another 21 wins & 15 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '15 Jun 1999',
//         'Director': 'Martin Scorsese',
//         'Genre': 'Crime, Drama',
//         'Language': 'English, Spanish',
//         'Metascore': '94',
//         'Plot': "Travis Bickle is an ex-Marine and Vietnam War veteran living in New York City. As he suffers from insomnia, he spends his time working as a taxi driver at night, watching porn movies at seedy cinemas during the day, or thinking about how the world, New York in particular, has deteriorated into a cesspool. He's a loner who has strong opinions about what is right and wrong with mankind. For him, the one bright spot in New York humanity is Betsy, a worker on the presidential nomination campaign of Senator Charles Palantine. He becomes obsessed with her. After an incident with her, he believes he has to do whatever he needs to make the world a better place in his opinion. One of his priorities is to be the savior for Iris, a twelve-year-old runaway and prostitute who he believes wants out of the profession and under the thumb of her pimp and lover Matthew.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'Columbia Pictures',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.3/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '98%'
//         }, {'Source': 'Metacritic', 'Value': '94/100'}],
//         'Released': '08 Feb 1976',
//         'Response': 'true',
//         'Runtime': '114 min',
//         'Title': 'Taxi Driver',
//         'Type': 'movie',
//         'Website': 'N/A',
//         'Writer': 'Paul Schrader',
//         'Year': '1976',
//         'favorite': true,
//         'imdbID': 'tt0075314',
//         'imdbRating': '8.3',
//         'imdbVotes': '639,223'
//     }, {
//         'Actors': 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta',
//         'Awards': 'Won 1 Oscar. Another 62 wins & 69 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '19 May 1998',
//         'Director': 'Quentin Tarantino',
//         'Genre': 'Crime, Drama',
//         'Language': 'English, Spanish, French',
//         'Metascore': '94',
//         'Plot': 'Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'Miramax Films',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.9/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '92%'
//         }, {'Source': 'Metacritic', 'Value': '94/100'}],
//         'Released': '14 Oct 1994',
//         'Response': 'true',
//         'Runtime': '154 min',
//         'Title': 'Pulp Fiction',
//         'Type': 'movie',
//         'Website': 'N/A',
//         'Writer': 'Quentin Tarantino (stories), Roger Avary (stories), Quentin Tarantino',
//         'Year': '1994',
//         'favorite': true,
//         'imdbID': 'tt0110912',
//         'imdbRating': '8.9',
//         'imdbVotes': '1,645,131'
//     }, {
//         'Actors': 'Samuel L. Jackson, Kurt Russell, Jennifer Jason Leigh, Walton Goggins',
//         'Awards': 'Won 1 Oscar. Another 39 wins & 113 nominations.',
//         'BoxOffice': '$54,116,191',
//         'Country': 'USA',
//         'DVD': '29 Mar 2016',
//         'Director': 'Quentin Tarantino',
//         'Genre': 'Crime, Drama, Mystery, Thriller, Western',
//         'Language': 'English, Spanish, French',
//         'Metascore': '68',
//         'Plot': "Some time after the Civil War, a stagecoach hurtles through the wintry Wyoming landscape. Bounty hunter John Ruth and his fugitive captive Daisy Domergue race towards the town of Red Rock, where Ruth will bring Daisy to justice. Along the road, they encounter Major Marquis Warren (an infamous bounty hunter) and Chris Mannix (a man who claims to be Red Rock's new sheriff). Lost in a blizzard, the bunch seeks refuge at Minnie's Haberdashery. When they arrive they are greeted by unfamiliar faces: Bob, who claims to be taking care of the place while Minnie is gone; Oswaldo Mobray, the hangman of Red Rock; Joe Gage, a cow puncher; and confederate general Sanford Smithers. As the storm overtakes the mountainside, the eight travelers come to learn that they might not make it to Red Rock after all...",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMjA1MTc1NTg5NV5BMl5BanBnXkFtZTgwOTM2MDEzNzE@._V1_SX300.jpg',
//         'Production': 'The Weinstein Company',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.8/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '74%'
//         }, {'Source': 'Metacritic', 'Value': '68/100'}],
//         'Released': '30 Dec 2015',
//         'Response': 'true',
//         'Runtime': '168 min',
//         'Title': 'The Hateful Eight',
//         'Type': 'movie',
//         'Website': 'http://thehatefuleight.com/',
//         'Writer': 'Quentin Tarantino',
//         'Year': '2015',
//         'favorite': true,
//         'imdbID': 'tt3460252',
//         'imdbRating': '7.8',
//         'imdbVotes': '435,766'
//     }, {
//         'Actors': 'Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah',
//         'Awards': 'Nominated for 1 Golden Globe. Another 27 wins & 99 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '13 Apr 2004',
//         'Director': 'Quentin Tarantino',
//         'Genre': 'Action, Crime, Thriller',
//         'Language': 'English, Japanese, French',
//         'Metascore': '69',
//         'Plot': "The lead character, called 'The Bride,' was a member of the Deadly Viper Assassination Squad, led by her lover 'Bill.' Upon realizing she was pregnant with Bill's child, 'The Bride' decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, 'The Bride' wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'Miramax Films',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.1/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '84%'
//         }, {'Source': 'Metacritic', 'Value': '69/100'}],
//         'Released': '10 Oct 2003',
//         'Response': 'true',
//         'Runtime': '111 min',
//         'Title': 'Kill Bill: Vol. 1',
//         'Type': 'movie',
//         'Website': 'http://www.kill-bill.com/',
//         'Writer': 'Quentin Tarantino, Quentin Tarantino (character The Bride), Uma Thurman (character The Bride)',
//         'Year': '2003',
//         'favorite': true,
//         'imdbID': 'tt0266697',
//         'imdbRating': '8.1',
//         'imdbVotes': '905,499'
//     }, {
//         'Actors': 'Vivica A. Fox, Ambrosia Kelley, Michael Parks, James Parks',
//         'Awards': 'Nominated for 2 Golden Globes. Another 21 wins & 81 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '10 Aug 2004',
//         'Director': 'Quentin Tarantino',
//         'Genre': 'Action, Crime, Thriller',
//         'Language': 'English, Cantonese, Mandarin, Spanish',
//         'Metascore': '83',
//         'Plot': "The murderous Bride is back and she is still continuing her vengeance quest against her ex-boss, Bill, and taking aim at Bill's younger brother Budd and Elle Driver, the only survivors from the squad of assassins who betrayed her four years earlier. It's all leading up to the ultimate confrontation with Bill, the Bride's former master and the man who ordered her execution!",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNmFiYmJmN2QtNWQwMi00MzliLThiOWMtZjQxNGRhZTQ1MjgyXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg',
//         'Production': 'Miramax Films',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '84%'
//         }, {'Source': 'Metacritic', 'Value': '83/100'}],
//         'Released': '16 Apr 2004',
//         'Response': 'true',
//         'Runtime': '137 min',
//         'Title': 'Kill Bill: Vol. 2',
//         'Type': 'movie',
//         'Website': 'http://www.kill-bill.com/',
//         'Writer': 'Quentin Tarantino, Quentin Tarantino (character The Bride), Uma Thurman (character The Bride)',
//         'Year': '2004',
//         'favorite': true,
//         'imdbID': 'tt0378194',
//         'imdbRating': '8.0',
//         'imdbVotes': '616,609'
//     }, {
//         'Actors': 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine',
//         'Awards': 'Won 2 Oscars. Another 152 wins & 155 nominations.',
//         'BoxOffice': '$533,316,061',
//         'Country': 'USA, UK',
//         'DVD': '09 Dec 2008',
//         'Director': 'Christopher Nolan',
//         'Genre': 'Action, Crime, Drama, Thriller',
//         'Language': 'English, Mandarin',
//         'Metascore': '84',
//         'Plot': 'Set within a year after the events of Batman Begins, Batman, Lieutenant James Gordon, and new district attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City until a mysterious and sadistic criminal mastermind known only as the Joker appears in Gotham, creating a new wave of chaos. Batman\'s struggle against the Joker becomes deeply personal, forcing him to "confront everything he believes" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent and Rachel Dawes.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg',
//         'Production': 'Warner Bros. Pictures/Legendary',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '9.0/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '94%'
//         }, {'Source': 'Metacritic', 'Value': '84/100'}],
//         'Released': '18 Jul 2008',
//         'Response': 'true',
//         'Runtime': '152 min',
//         'Title': 'The Dark Knight',
//         'Type': 'movie',
//         'Website': 'http://thedarkknight.warnerbros.com/',
//         'Writer': 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)',
//         'Year': '2008',
//         'favorite': true,
//         'imdbID': 'tt0468569',
//         'imdbRating': '9.0',
//         'imdbVotes': '2,070,977'
//     }, {
//         'Actors': 'Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt',
//         'Awards': 'Nominated for 1 BAFTA Film Award. Another 38 wins & 102 nominations.',
//         'BoxOffice': '$448,130,642',
//         'Country': 'UK, USA',
//         'DVD': '03 Dec 2012',
//         'Director': 'Christopher Nolan',
//         'Genre': 'Action, Thriller',
//         'Language': 'English, Arabic',
//         'Metascore': '78',
//         'Plot': "Despite his tarnished reputation after the events of The Dark Knight, in which he took the rap for Dent's crimes, Batman feels compelled to intervene to assist the city and its police force which is struggling to cope with Bane's plans to destroy the city.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg',
//         'Production': 'Warner Bros. Pictures',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.4/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '87%'
//         }, {'Source': 'Metacritic', 'Value': '78/100'}],
//         'Released': '20 Jul 2012',
//         'Response': 'true',
//         'Runtime': '164 min',
//         'Title': 'The Dark Knight Rises',
//         'Type': 'movie',
//         'Website': 'http://www.thedarkknightrises.com/',
//         'Writer': 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)',
//         'Year': '2012',
//         'favorite': true,
//         'imdbID': 'tt1345836',
//         'imdbRating': '8.4',
//         'imdbVotes': '1,389,960'
//     }, {
//         'Actors': 'Alan Howard, Noel Appleby, Sean Astin, Sala Baker',
//         'Awards': 'Won 4 Oscars. Another 113 wins & 123 nominations.',
//         'BoxOffice': '$314,000,000',
//         'Country': 'New Zealand, USA',
//         'DVD': '06 Aug 2002',
//         'Director': 'Peter Jackson',
//         'Genre': 'Adventure, Drama, Fantasy',
//         'Language': 'English, Sindarin',
//         'Metascore': '92',
//         'Plot': 'An ancient Ring thought lost for centuries has been found, and through a strange twist in fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it! However he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir and his three Hobbit friends Merry, Pippin and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign!',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
//         'Production': 'New Line Cinema',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.8/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '91%'
//         }, {'Source': 'Metacritic', 'Value': '92/100'}],
//         'Released': '19 Dec 2001',
//         'Response': 'true',
//         'Runtime': '178 min',
//         'Title': 'The Lord of the Rings: The Fellowship of the Ring',
//         'Type': 'movie',
//         'Website': 'http://www.lordoftherings.net/film/trilogy/thefellowship.html',
//         'Writer': 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)',
//         'Year': '2001',
//         'favorite': true,
//         'imdbID': 'tt0120737',
//         'imdbRating': '8.8',
//         'imdbVotes': '1,514,088'
//     }, {
//         'Actors': 'Noel Appleby, Ali Astin, Sean Astin, David Aston',
//         'Awards': 'Won 11 Oscars. Another 197 wins & 122 nominations.',
//         'BoxOffice': '$364,000,000',
//         'Country': 'New Zealand, USA',
//         'DVD': '25 May 2004',
//         'Director': 'Peter Jackson',
//         'Genre': 'Adventure, Drama, Fantasy',
//         'Language': 'English, Quenya, Old English, Sindarin',
//         'Metascore': '94',
//         'Plot': 'The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits: Frodo and Sam reach Mordor in their quest to destroy the "one ring", while Aragorn leads the forces of good against Sauron\'s evil army at the stone city of Minas Tirith.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'New Line Cinema',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.9/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '93%'
//         }, {'Source': 'Metacritic', 'Value': '94/100'}],
//         'Released': '17 Dec 2003',
//         'Response': 'true',
//         'Runtime': '201 min',
//         'Title': 'The Lord of the Rings: The Return of the King',
//         'Type': 'movie',
//         'Website': 'http://www.lordoftherings.net/',
//         'Writer': 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)',
//         'Year': '2003',
//         'favorite': true,
//         'imdbID': 'tt0167260',
//         'imdbRating': '8.9',
//         'imdbVotes': '1,499,774'
//     }, {
//         'Actors': 'Bruce Allpress, Sean Astin, John Bach, Sala Baker',
//         'Awards': 'Won 2 Oscars. Another 118 wins & 137 nominations.',
//         'BoxOffice': '$339,700,000',
//         'Country': 'New Zealand, USA',
//         'DVD': '26 Aug 2003',
//         'Director': 'Peter Jackson',
//         'Genre': 'Adventure, Drama, Fantasy',
//         'Language': 'English, Sindarin, Old English',
//         'Metascore': '87',
//         'Plot': 'While Frodo and Sam, now accompanied by a new guide, continue their hopeless journey towards the land of shadow to destroy the One Ring, each member of the broken fellowship plays their part in the battle against the evil wizard Saruman and his armies of Isengard.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': 'New Line Cinema',
//         'Rated': 'PG',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.7/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '95%'
//         }, {'Source': 'Metacritic', 'Value': '87/100'}],
//         'Released': '18 Dec 2002',
//         'Response': 'true',
//         'Runtime': '179 min',
//         'Title': 'The Lord of the Rings: The Two Towers',
//         'Type': 'movie',
//         'Website': 'http://www.lordoftherings.net/',
//         'Writer': 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Stephen Sinclair (screenplay), Peter Jackson (screenplay)',
//         'Year': '2002',
//         'favorite': true,
//         'imdbID': 'tt0167261',
//         'imdbRating': '8.7',
//         'imdbVotes': '1,355,308'
//     }, {
//         'Actors': "Jerry O'Connell, Rebecca Romijn, Rainn Wilson, Rosario Dawson",
//         'Awards': 'N/A',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '02 Oct 2018',
//         'Director': 'Jake Castorena, Sam Liu',
//         'Genre': 'Animation, Action, Sci-Fi',
//         'Language': 'English',
//         'Metascore': 'N/A',
//         'Plot': 'Superman battles against an insurmountable foe named Doomsday.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BNWZkMjYzNjctYTMyZi00MjdjLTg5MzMtYjdhM2M0MTI5ZWFkXkEyXkFqcGdeQXVyNTc4MjczMTM@._V1_SX300.jpg',
//         'Production': 'N/A',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '92%'
//         }],
//         'Released': '24 Jul 2018',
//         'Response': 'true',
//         'Runtime': '81 min',
//         'Title': 'The Death of Superman',
//         'Type': 'movie',
//         'Website': 'N/A',
//         'Writer': 'Peter Tomasi, Jerry Siegel (character created by: Superman), Joe Shuster (character created by: Superman), Paul Norris (character created by: Aquaman), Bob Kane (character created by: Batman), Bill Finger (character created by: Batman), Marv Wolfman (characters created by: Bibbo Bibbowski and Cat Grant), Jerry Ordway (characters created by: Bibbo Bibbowski and Cat Grant), Marv Wolfman (characters created by: Cyborg and Silas Stone), George Pérez (characters created by: Cyborg and Silas Stone), Brett Breeding (character created by: Doomsday), Jerry Ordway (character created by: Doomsday), Louise Simonson (character created by: Doomsday), Roger Stern (character created by: Doomsday), Dan Jurgens (character created by: Doomsday), Jack Kirby (characters created by: Fourth World), Louise Simonson (character created by: John Henry Irons), Jon Bogdanove (character created by: John Henry Irons), Dan Jurgens (character created by: Hank Henshaw), John Byrne (character created by: Maggie Sawyer), Joe Samachson (character created by: Martian Manhunter), Joe Certa (character created by: Martian Manhunter), William Moulton Marston (character created by: Wonder Woman)',
//         'Year': '2018',
//         'favorite': true,
//         'imdbID': 'tt7167658',
//         'imdbRating': '7.4',
//         'imdbVotes': '9,104'
//     }, {
//         'Actors': 'Zachary Levi, Mark Strong, Asher Angel, Jack Dylan Grazer',
//         'Awards': 'N/A',
//         'BoxOffice': 'N/A',
//         'Country': 'USA',
//         'DVD': '16 Jul 2019',
//         'Director': 'David F. Sandberg',
//         'Genre': 'Action, Adventure, Comedy, Fantasy',
//         'Language': 'English',
//         'Metascore': '70',
//         'Plot': 'Young Billy Batson finds himself gifted with the power of the wizard Shazam to fight against the forces of evil. With the wisdom of Solomon, the strength of Hercules, the stamina of Atlas, the power of Zeus, the courage of Achilles and speed of Mercury, he is the holder of the power of S.H.A.Z.A.M; he is Captain Marvel.',
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BYTE0Yjc1NzUtMjFjMC00Y2I3LTg3NGYtNGRlMGJhYThjMTJmXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg',
//         'Production': 'New Line Cinema',
//         'Rated': 'PG-13',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '91%'
//         }, {'Source': 'Metacritic', 'Value': '70/100'}],
//         'Released': '05 Apr 2019',
//         'Response': 'true',
//         'Runtime': '132 min',
//         'Title': 'Shazam!',
//         'Type': 'movie',
//         'Website': 'http://ShazamMovie.com',
//         'Writer': 'Henry Gayden (screenplay by), Henry Gayden (story by), Darren Lemke (story by), Bill Parker (Shazam created by), C.C. Beck (Shazam created by)',
//         'Year': '2019',
//         'favorite': true,
//         'imdbID': 'tt0448115',
//         'imdbRating': '7.4',
//         'imdbVotes': '108,101'
//     }, {
//         'Actors': 'Edward Norton, Brad Pitt, Meat Loaf, Zach Grenier',
//         'Awards': 'Nominated for 1 Oscar. Another 10 wins & 34 nominations.',
//         'BoxOffice': 'N/A',
//         'Country': 'USA, Germany',
//         'DVD': '06 Jun 2000',
//         'Director': 'David Fincher',
//         'Genre': 'Drama',
//         'Language': 'English',
//         'Metascore': '66',
//         'Plot': "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power. When the narrator is exposed to the hidden agenda of Tyler's fight club, he must accept the awful truth that Tyler may not be who he says he is.",
//         'Poster': 'https://m.media-amazon.com/images/M/MV5BMjJmYTNkNmItYjYyZC00MGUxLWJhNWMtZDY4Nzc1MDAwMzU5XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
//         'Production': '20th Century Fox',
//         'Rated': 'R',
//         'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.8/10'}, {
//             'Source': 'Rotten Tomatoes',
//             'Value': '79%'
//         }, {'Source': 'Metacritic', 'Value': '66/100'}],
//         'Released': '15 Oct 1999',
//         'Response': 'true',
//         'Runtime': '139 min',
//         'Title': 'Fight Club',
//         'Type': 'movie',
//         'Website': 'http://www.foxmovies.com/fightclub/',
//         'Writer': 'Chuck Palahniuk (novel), Jim Uhls (screenplay)',
//         'Year': '1999',
//         'favorite': true,
//         'imdbID': 'tt0137523',
//         'imdbRating': '8.8',
//         'imdbVotes': '1,678,634'
//     }]
// };